/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Response type discriminator
 */
export type Type =
  | "error"
  | "completion.response"
  | "completion.chunk"
  | "completion.usage"
  | "completion.sources"
  | "completion.hitl.request"
  | "event"
  | "confirmation"
  | string;
/**
 * Response content
 */
export type Content = string | number | null;
/**
 * Message role
 */
export type MessageRole = "user" | "assistant" | "system";
/**
 * Message content
 */
export type Content1 = string;
/**
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "MessageRole".
 */
export type MessageRole1 = "user" | "assistant" | "system";
/**
 * User message to process
 */
export type Message = string;
/**
 * Chat history for context
 */
export type ChatHistory = ChatMessageBase[];
/**
 * Enable Phoenix observability for this request
 */
export type Observability = boolean | null;
/**
 * List of file paths to process
 */
export type FileUploads = string[] | null;
/**
 * Working folder path
 */
export type WorkingFolder = string | null;
/**
 * Subset of documents in vector database
 */
export type KnowledgeHubs = string[] | null;
/**
 * Health status
 */
export type Status = "ok";
/**
 * Workflow name identifier
 */
export type Name = string;
/**
 * Workflow description
 */
export type Description = string;
/**
 * Path to workflow file
 */
export type Path = string;
/**
 * File being processed
 */
export type Filename = string;
/**
 * Processing progress percentage
 */
export type Progress = number;
/**
 * Number of files processed
 */
export type Processed = number;
/**
 * Total files to process
 */
export type Total = number;
/**
 * Error message if processing failed
 */
export type Error = string | null;
/**
 * The highlighted content
 */
export type Content2 = string;
/**
 * Content format type
 */
export type Type1 = "code" | "markdown" | "plain";
/**
 * Unique artifact identifier
 */
export type Id = string;
/**
 * Artifact content
 */
export type Content3 = string;
/**
 * Storage type discriminator
 */
export type Type2 = "VectorStore" | "DocumentStore";
/**
 * Vector store or document store ID
 */
export type Id1 = string;
/**
 * Storage client identifier
 */
export type Client = "qdrant" | "mongodb" | string;

export interface ApiSchemas {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "DefaultResponse".
 */
export interface DefaultResponse {
  type: Type;
  payload?: unknown;
  content?: Content;
}
/**
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "ChatMessageBase".
 */
export interface ChatMessageBase {
  role: MessageRole;
  content: Content1;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "ChatCompletionRequest".
 */
export interface ChatCompletionRequest {
  message: Message;
  chat_history?: ChatHistory;
  observability?: Observability;
  file_uploads?: FileUploads;
  working_folder?: WorkingFolder;
  knowledge_hubs?: KnowledgeHubs;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "HealthResponse".
 */
export interface HealthResponse {
  status: Status;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "WorkflowInfo".
 */
export interface WorkflowInfo {
  name: Name;
  description?: Description;
  path: Path;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "EmbeddingProgress".
 */
export interface EmbeddingProgress {
  filename: Filename;
  progress: Progress;
  processed: Processed;
  total: Total;
  error?: Error;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "TextHighlight".
 */
export interface TextHighlight {
  content: Content2;
  type?: Type1;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "Artifact".
 */
export interface Artifact {
  id?: Id;
  content: Content3;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ApiSchemas`'s JSON-Schema
 * via the `definition` "KnowledgeGraphOrStorage".
 */
export interface KnowledgeGraphOrStorage {
  type?: Type2;
  id: Id1;
  client: Client;
  [k: string]: unknown;
}
