// This file is generated by scripts/generate_sqlite_types.py.
// Do not edit directly.

export type TableName =
  | 'projects'
  | 'conversations'
  | 'messages'
  | 'artifacts'
  | 'artifact_revisions'
  | 'llm_providers'
  | 'app_settings'

export interface Project {
  id: string
  name: string
  folder_path: string | null
  created_at: number
  updated_at: number
}

export interface Conversation {
  id: string
  project_id: string
  title: string | null
  active_artifact_id: string | null
  created_at: number
  updated_at: number
}

export interface Message {
  id: string
  conversation_id: string
  role: 'user' | 'assistant' | 'system'
  content: string
  metadata: string | null
  sequence_order: number
  created_at: number
}

export interface Artifact {
  id: string
  conversation_id: string
  title: string | null
  current_revision_id: string | null
  file_path: string | null
  file_hash: string | null
  created_at: number
  updated_at: number
}

export interface ArtifactRevision {
  id: string
  artifact_id: string
  message_id: string | null
  author: 'user' | 'ai'
  content: string
  created_at: number
  updated_at: number
}

export interface LlmProvider {
  id: string
  name: string
  provider_type: string
  base_url: string
  api_key: string | null
  is_default: number
  created_at: number
}

export interface AppSetting {
  key: string
  value: string
}
