import argparse
import re
import sqlite3
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SQL_PATH = ROOT / "src-tauri" / "migrations" / "001_initial.sql"
DEFAULT_OUTPUT_PATH = ROOT / "src" / "lib" / "db" / "schema-types.ts"

INTERFACE_NAMES = {
    "projects": "Project",
    "conversations": "Conversation",
    "messages": "Message",
    "artifacts": "Artifact",
    "artifact_revisions": "ArtifactRevision",
    "llm_providers": "LlmProvider",
    "app_settings": "AppSetting",
}

TYPE_OVERRIDES = {
    ("messages", "role"): "'user' | 'assistant' | 'system'",
    ("artifact_revisions", "author"): "'user' | 'ai'",
}


def quote_identifier(identifier: str) -> str:
    return f'"{identifier.replace(chr(34), chr(34) * 2)}"'


def sqlite_type_to_typescript(sqlite_type: str) -> str:
    normalized = re.sub(r"\(.*\)", "", sqlite_type.upper()).strip()

    if "INT" in normalized:
        return "number"
    if any(token in normalized for token in ("CHAR", "CLOB", "TEXT")):
        return "string"
    if any(token in normalized for token in ("REAL", "FLOA", "DOUB")):
        return "number"
    if "BLOB" in normalized:
        return "Uint8Array"
    if any(token in normalized for token in ("NUM", "DEC", "BOOL")):
        return "number"

    return "unknown"


def table_to_interface_name(table_name: str) -> str:
    if table_name in INTERFACE_NAMES:
        return INTERFACE_NAMES[table_name]

    parts = table_name.removesuffix("s").split("_")
    return "".join(part.capitalize() for part in parts)


def introspect_schema(sql_path: Path) -> dict[str, list[sqlite3.Row]]:
    sql = sql_path.read_text()
    connection = sqlite3.connect(":memory:")
    connection.row_factory = sqlite3.Row

    try:
        connection.executescript(sql)
        table_rows = connection.execute(
            """
            SELECT name
            FROM sqlite_master
            WHERE type = 'table'
              AND name NOT LIKE 'sqlite_%'
            ORDER BY rowid
            """
        ).fetchall()

        schema: dict[str, list[sqlite3.Row]] = {}
        for row in table_rows:
            table_name = row["name"]
            schema[table_name] = connection.execute(
                f"PRAGMA table_info({quote_identifier(table_name)})"
            ).fetchall()
        return schema
    finally:
        connection.close()


def render_property(table_name: str, column: sqlite3.Row) -> str:
    column_name = column["name"]
    base_type = TYPE_OVERRIDES.get(
        (table_name, column_name),
        sqlite_type_to_typescript(column["type"]),
    )
    nullable = not (column["notnull"] or column["pk"])
    ts_type = f"{base_type} | null" if nullable else base_type
    return f"  {column_name}: {ts_type}"


def render_types(schema: dict[str, list[sqlite3.Row]]) -> str:
    table_names = list(schema.keys())
    lines = [
        "// This file is generated by scripts/generate_sqlite_types.py.",
        "// Do not edit directly.",
        "",
        "export type TableName =",
    ]

    for index, table_name in enumerate(table_names):
        separator = "" if index == len(table_names) - 1 else ""
        lines.append(f"  | '{table_name}'{separator}")

    for table_name, columns in schema.items():
        lines.append("")
        lines.append(f"export interface {table_to_interface_name(table_name)} {{")
        lines.extend(render_property(table_name, column) for column in columns)
        lines.append("}")

    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate TypeScript DB row types from the shared SQLite schema."
    )
    parser.add_argument("--sql", type=Path, default=DEFAULT_SQL_PATH)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT_PATH)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit with a non-zero status if the output file is stale.",
    )
    args = parser.parse_args()

    schema = introspect_schema(args.sql)
    generated = render_types(schema)

    if args.check:
        existing = args.output.read_text() if args.output.exists() else ""
        if existing != generated:
            print(f"{args.output} is stale. Run bun run db:generate.")
            return 1
        print(f"{args.output} is up to date.")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generated)
    print(f"Generated {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
